// <auto-generated />
namespace urbanbooks.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class fix00 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fix00));
        
        string IMigrationMetadata.Id
        {
            get { return "201408271240277_fix0.0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
