// <auto-generated />
namespace urbanbooks.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class fix0023 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fix0023));
        
        string IMigrationMetadata.Id
        {
            get { return "201408290945339_fix0023"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
