// <auto-generated />
namespace urbanbooks.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class tibs : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tibs));
        
        string IMigrationMetadata.Id
        {
            get { return "201409091849202_tibs"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
