// <auto-generated />
namespace urbanbooks.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class migration109 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migration109));
        
        string IMigrationMetadata.Id
        {
            get { return "201408291135008_migration109"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
